### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by 0000111100001111** [zer0int/ComfyUI-HunyuanVideo-Nyan#7]
No longer seems to work with recent versions of the Hunyuan Video Sampler node from HunyuanVideoWrapper.

`!!! Exception during processing !!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "e:\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "e:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "e:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 1112, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "e:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideo-Nyan\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 582, in __call__
    freqs_cos=freqs_cis[0],  # [seqlen, head_dim]
              ~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable`

**Comment by zer0int** [comment]
As there seem to be daily or even multiple daily updates to the original repo, I'd be chasing incompatibilities; alas, I will wait until "the dust settles" and it becomes more stable (less frequent updates).

Meanwhile, you can use my fork of the original repo that I made the node for:
https://github.com/zer0int/ComfyUI-HunyuanVideoWrapper
