### ISSUE TITLE
Compile node not working anymore..

### ISSUE THREAD

**Issue by perobueno** [zer0int/ComfyUI-HunyuanVideo-Nyan#8]
If I detach it it works.

**Comment by perobueno** [comment]
Okay I think I installed it corrrectly now but the compile node is not working for me. It was working last week. buyt now it just throws errors:

Import times for custom nodes:
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
   0.2 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.3 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KYNode
   0.4 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MMAudio
   0.6 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideo-Nyan
   0.7 seconds: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama_fast.LlamaTokenizerFast'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565 - if you loaded a llama tokenizer from a GGUF file you can ignore this message.
Loading text encoder model (vlm) from: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-v1_1-transformers
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:09<00:00,  2.32s/it]
Text encoder to dtype: torch.bfloat16
Loading tokenizer (vlm) from: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-v1_1-transformers
Expanding inputs for image tokens in LLaVa should be done in processing. Please add `patch_size` and `vision_feature_select_strategy` to the model's processing config or set directly with `processor.patch_size = {{patch_size}}` and processor.vision_feature_select_strategy = {{vision_feature_select_strategy}}`. Using processors without these attributes in the config is deprecated and will throw an error in v4.50.
Expanding inputs for image tokens in LLaVa should be done in processing. Please add `patch_size` and `vision_feature_select_strategy` to the model's processing config or set directly with `processor.patch_size = {{patch_size}}` and processor.vision_feature_select_strategy = {{vision_feature_select_strategy}}`. Using processors without these attributes in the config is deprecated and will throw an error in v4.50.
vlm prompt attention_mask shape: torch.Size([1, 188]), masked tokens: 188
Requested to load SD1ClipModel
loaded completely 9.5367431640625e+25 236.0947265625 True
Loading model from file...
model_type FLOW
Scheduler config: FrozenDict([('num_train_timesteps', 1000), ('shift', 9.0), ('reverse', True), ('solver', 'euler'), ('n_tokens', None), ('_use_default_values', ['num_train_timesteps', 'n_tokens'])])
Using accelerate to load and assign model weights to device...
Requested to load HyVideoModel
0 models unloaded.
loaded completely 64.0 63.8829345703125 False
Input (height, width, video_length) = (768, 1344, 1)
Swapping 20 double blocks and 0 single blocks
Sampling 1 frames in 1 latents at 1344x768 with 30 inference steps
  0%|                                                                                           | 0/30 [00:01<?, ?it/s]
!!! Exception during processing !!! backend='inductor' raised:
FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\.21484.34856.tmp' -> 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\781f1df97609b2d228357432b12d1cb39a49abf06c458cb7dee4c56c35c1fecd'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Traceback (most recent call last):
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 1446, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\__init__.py", line 2234, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1521, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\backends\common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_functorch\aot_autograd.py", line 1071, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_functorch\aot_autograd.py", line 1056, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_functorch\aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_functorch\aot_autograd.py", line 759, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1350, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 1359, in _fw_compiler_base
    _recursive_joint_graph_passes(model)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\compile_fx.py", line 281, in _recursive_joint_graph_passes
    joint_graph_passes(gm)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\fx_passes\joint_graph.py", line 460, in joint_graph_passes
    count += patterns.apply(graph.graph)  # type: ignore[arg-type]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\pattern_matcher.py", line 1729, in apply
    if is_match(m) and entry.extra_check(m):
                       ^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\pattern_matcher.py", line 1331, in check_fn
    if is_match(specific_pattern_match) and extra_check(specific_pattern_match):
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 146, in should_pad_addmm
    return should_pad_common(mat1, mat2, input) and should_pad_bench(
                                                    ^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 570, in should_pad_bench
    return should_pad(key, ori_time, pad_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 363, in should_pad
    set_cached_should_pad(key, should_pad)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 254, in set_cached_should_pad
    return get_pad_cache().set_value(key, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\codecache.py", line 286, in set_value
    self.update_local_cache(cache)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\codecache.py", line 257, in update_local_cache
    write_atomic(
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_inductor\codecache.py", line 466, in write_atomic
    tmp_path.rename(path)
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1175, in rename
    os.rename(self, target)
FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\.21484.34856.tmp' -> 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\781f1df97609b2d228357432b12d1cb39a49abf06c458cb7dee4c56c35c1fecd'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 1143, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideo-Nyan\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 732, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideo-Nyan\hyvideo\modules\models.py", line 951, in forward
    img, txt = block(*double_block_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1269, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1064, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 526, in __call__
    return _compile(
           ^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\convert_frame.py", line 634, in transform
    tracer.run()
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2796, in run
    super().run()
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 580, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 649, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 1142, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 1369, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 1416, in call_user_compiler
    return self._call_user_compiler(gm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\torch\_dynamo\output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\.21484.34856.tmp' -> 'C:\\Users\\marcelo\\AppData\\Local\\Temp\\torchinductor_marcelo\\cache\\781f1df97609b2d228357432b12d1cb39a49abf06c458cb7dee4c56c35c1fecd'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by perobueno** [comment]
Keep in mind the node works on kijai's workflow.

**Comment by zer0int** [comment]
```
FileExistsError: [WinError 183] No se puede crear un archivo que ya existe: 'C:\Users\marcelo\AppData\Local\Temp\torchinductor_marcelo\cache\.21484.34856.tmp' -> 'C:\Users\marcelo\AppData\Local\Temp\torchinductor_marcelo\cache\781f1df97609b2d228357432b12d1cb39a49abf06c458cb7dee4c56c35c1fecd'
```

That is actually an issue with PyTorch and Windows (the error is 'can't overwrite already existing file'), it seems. 
Although there may be other workarounds, see here for a simple fix:

https://github.com/zer0int/ComfyUI-HunyuanVideo-Nyan/issues/6

As you can see in the link to the source, this occurs in different contexts, so it's probably best to just fix the issue with PyTorch, or you might have it again in some other context.
